// Backs up the hosted (Neon) database to data/backups/<date>.json without touching the
// local SQLite client. Needs DATABASE_URL_NEON in .env and the side Postgres client
// (node_modules/.prisma/client-pg, generated by docs/DEPLOY.md step 2).
//   npm run db:backup
// Restore into a fresh database with import-db.ts (point it at the backup file via
// IMPORT_FILE=data/backups/<date>.json).
import "dotenv/config";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const url = process.env.DATABASE_URL_NEON;
if (!url) {
  console.error("DATABASE_URL_NEON is not set in .env");
  process.exit(1);
}
process.env.DATABASE_URL = url;
const clientPath = join(process.cwd(), "node_modules", ".prisma", "client-pg");
if (!existsSync(clientPath)) {
  console.error(`Postgres client missing. Run: npx prisma generate --schema=prisma/schema.postgres.local.prisma`);
  process.exit(1);
}
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { PrismaClient } = require(clientPath) as typeof import("@prisma/client");
const db = new PrismaClient();

async function main() {
  const out = {
    exportedAt: new Date().toISOString(),
    source: "neon",
    contests: await db.contest.findMany(),
    topics: await db.topic.findMany(),
    skills: await db.skill.findMany(),
    problems: await db.problem.findMany(),
    problemTopics: await db.problemTopic.findMany(),
    problemSkills: await db.problemSkill.findMany(),
    solutions: await db.solution.findMany(),
    users: await db.user.findMany(),
    studyPlans: await db.studyPlan.findMany(),
    skillMasteries: await db.skillMastery.findMany(),
    worksheets: await db.worksheet.findMany(),
    studySessions: await db.studySession.findMany(),
    attempts: await db.attempt.findMany(),
    reviewItems: await db.reviewItem.findMany(),
    lessonProgress: await db.lessonProgress.findMany(),
    lessonViews: await db.lessonView.findMany(),
    mockExams: await db.mockExam.findMany(),
  };
  const dir = join(process.cwd(), "data", "backups");
  mkdirSync(dir, { recursive: true });
  const stamp = new Date().toISOString().slice(0, 19).replace(/[:T]/g, "-");
  const file = join(dir, `neon-${stamp}.json`);
  writeFileSync(file, JSON.stringify(out));
  console.log(`backup written: ${file}`);
  console.log(`users=${out.users.length} attempts=${out.attempts.length} worksheets=${out.worksheets.length} lessonProgress=${out.lessonProgress.length} problems=${out.problems.length}`);
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
